#!/bin/bash
set -e

echo "🚀 Starting Mattermost..."

cd mattermost

# PostgreSQL configuration
export MM_SQLSETTINGS_DRIVERNAME="postgres"
export MM_SQLSETTINGS_DATASOURCE="postgres://${POSTGRESQL_ADDON_USER}:${POSTGRESQL_ADDON_PASSWORD}@${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}?sslmode=require&connect_timeout=10"

# Service configuration - IMPORTANT: listen on 0.0.0.0:8080
export MM_SERVICESETTINGS_LISTENADDRESS="0.0.0.0:8080"
export MM_SERVICESETTINGS_SITEURL="${SITE_URL}"

# S3 (Cellar) Storage configuration
export MM_FILESETTINGS_DRIVERNAME="amazons3"
export MM_FILESETTINGS_AMAZONS3ACCESSKEYID="${CELLAR_ADDON_KEY_ID}"
export MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY="${CELLAR_ADDON_KEY_SECRET}"
export MM_FILESETTINGS_AMAZONS3BUCKET="${CELLAR_BUCKET}"
export MM_FILESETTINGS_AMAZONS3ENDPOINT="${CELLAR_ADDON_HOST}"
export MM_FILESETTINGS_AMAZONS3REGION="us-east-1"
export MM_FILESETTINGS_AMAZONS3SSL="true"
export MM_FILESETTINGS_AMAZONS3SIGNV2="false"
export MM_FILESETTINGS_AMAZONS3SSE="false"

# Email configuration
export MM_EMAILSETTINGS_SENDEMAILNOTIFICATIONS="true" 
export MM_EMAILSETTINGS_ENABLEPREVIEWMODEBANNER="false"

#  SMTP configuration - replace with your SMTP server details
export MM_EMAILSETTINGS_SMTPSERVER="${MM_EMAILSETTINGS_SMTPSERVER}"
export MM_EMAILSETTINGS_SMTPPORT="${MM_EMAILSETTINGS_SMTPPORT}"

# Authentication for SMTP
export MM_EMAILSETTINGS_ENABLESMTPAUTH="true"
export MM_EMAILSETTINGS_SMTPUSERNAME="${MM_EMAILSETTINGS_SMTPUSERNAME}"
export MM_EMAILSETTINGS_SMTPPASSWORD="${MM_EMAILSETTINGS_SMTPPASSWORD}"

# Connection security (STARTTLS, TLS, or SSL)
export MM_EMAILSETTINGS_CONNECTIONSECURITY="${MM_EMAILSETTINGS_CONNECTIONSECURITY}"

# Email address for notifications
export MM_EMAILSETTINGS_FEEDBACKNAME="${MM_EMAILSETTINGS_FEEDBACKNAME}"
export MM_EMAILSETTINGS_FEEDBACKEMAIL="${MM_EMAILSETTINGS_FEEDBACKEMAIL}"
export MM_EMAILSETTINGS_REPLYTOADDRESS="${MM_EMAILSETTINGS_REPLYTOADDRESS}"
export MM_SUPPORTSETTINGS_SUPPORTEMAIL="${MM_SUPPORTSETTINGS_SUPPORTEMAIL}"

# Logs on stdout for Clever Cloud
export MM_LOGSETTINGS_ENABLECONSOLE="true"
export MM_LOGSETTINGS_CONSOLELEVEL="INFO"
export MM_LOGSETTINGS_CONSOLEJSON="true"

echo "✅ Configuration loaded"
echo "📊 Database: ${POSTGRESQL_ADDON_HOST}:${POSTGRESQL_ADDON_PORT}/${POSTGRESQL_ADDON_DB}"
echo "🪣 S3 stockage: ${CELLAR_ADDON_HOST}/${CELLAR_BUCKET}"
echo "🌐 URL website: ${SITE_URL}"
echo "🎧 Listening on: 0.0.0.0:8080"

# Start Mattermost
exec ./bin/mattermost

